---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/app-menu: development
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    expose: "true"
  name: "fabric8-runtime-console"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8001
  selector:
    project: "fabric8-runtime-console"
    provider: "fabric8"
